{% set name = "dwclib" %}
{% set version = "2024.12.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbdf7107d3647438a695a14f78201dd07300c1bf317e88c1cb3bf6735defa5ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python >=3.9,<4
    - pip
    - setuptools
    - poetry >=0.12
  run:
    - numpy >=2,<3
    - pandas >=2,<3
    - dask >=2024
    - platformdirs >=3,<4
    - psycopg2 >=2.9.9
    - pyarrow >=14
    - python >=3.9,<4
    - sqlalchemy >=2,<3
    - pymssql >=2.3,<3

test:
  imports:
    - dwclib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/larib-data/dwclib
  summary: Python wrapper to DataWarehouse Connect
  description: |
    dwclib is a Python library which enables queries against Philips
    DataWarehouse Connect databases in a simple and fast manner.
    Numerics and Waveform data can be queried and is returned as pandas
    dataframes. Optional dask support is included in the library.
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/larib-data/dwclib

extra:
  recipe-maintainers:
    - jaj42
