{% set name = "dwclib" %}
{% set version = "2024.9.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eebf38ff08e320548028b4eb460d7158013c8c67a433d71e1bd045cdafe5c360

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - poetry >=0.12
  run:
    - numpy >=2,<3
    - pandas >=2,<3
    - dask >=2024
    - platformdirs >=3,<4
    - psycopg2 >=2.9.9
    - pyarrow >=14
    - python >={{ python_min }},<4
    - sqlalchemy >=2,<3
    - pymssql >=2.3,<3

test:
  imports:
    - dwclib
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/larib-data/dwclib
  summary: Python wrapper to DataWarehouse Connect
  description: |
    dwclib is a Python library which enables queries against Philips
    DataWarehouse Connect databases in a simple and fast manner.
    Numerics and Waveform data can be queried and is returned as pandas
    dataframes. Optional dask support is included in the library.
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/larib-data/dwclib

extra:
  recipe-maintainers:
    - jaj42
